# Generated by Django 2.0.13 on 2019-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=100, null=True, verbose_name='Autor')),
                ('mensaje', models.TextField(null=True, verbose_name='Mensaje')),
            ],
        ),
    ]
