# Generated by Django 2.0.13 on 2019-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo Mensaje'),
        ),
    ]
